/**
 * EazyShop Products APIs Definition
 * # About Us **EazyShop** is a open market product selling company. Any website can list our products by  using our _APIs_. Shipping & other logistics will be taken care by us. You will get an `Affiliate commision` for selling our products. # Categories suported   - Mobiles     - Apple     - Samsung     - OnePlus   - Laptops   - Televisions   - Headphones 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@eazyshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Address { 
    addressLine: string;
    city: string;
    state: Address.StateEnum;
    zipcode: string;
    isOfficeAddress?: boolean;
}
export namespace Address {
    export type StateEnum = 'California' | 'Texas' | 'Indiana' | 'NewYork';
    export const StateEnum = {
        California: 'California' as StateEnum,
        Texas: 'Texas' as StateEnum,
        Indiana: 'Indiana' as StateEnum,
        NewYork: 'NewYork' as StateEnum
    };
}