/**
 * EazyShop Products APIs Definition
 * # About Us **EazyShop** is a open market product selling company. Any website can list our products by  using our _APIs_. Shipping & other logistics will be taken care by us. You will get an `Affiliate commision` for selling our products. # Categories suported   - Mobiles     - Apple     - Samsung     - OnePlus   - Laptops   - Televisions   - Headphones 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@eazyshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Product } from './product';

export interface Laptop extends Product { 
    ram: Laptop.RamEnum;
}
export namespace Laptop {
    export type RamEnum = '8 GB' | '16 GB' | '32 GB';
    export const RamEnum = {
        _8GB: '8 GB' as RamEnum,
        _16GB: '16 GB' as RamEnum,
        _32GB: '32 GB' as RamEnum
    };
}